runtime: nodejs20

env: standard

# Variables de entorno
env_variables:
  PORT: 3000

# Handlers
handlers:
- url: /.*
  script: auto

jobs:
  build_app: 
    uses: ./.github/workflows/gcp-deploy.yaml
    with:
      input_key: value
    secrets: inherit