substitutions:
  _REPO_NAME: ''
  _COMMIT_SHA: 'latest'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_REPO_NAME:$_COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_REPO_NAME:$_COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$_REPO_NAME:$_COMMIT_SHA']